python: Do not add standard library path to PYTHONPATH
Adding the standard library to PYTHONPATH causes strange errors when
invoking a Python interpreter based on a different Python version. In
any case, it is not necessary to add it to PYTHONPATH, because it is
always searched regardless, according to the following excerpt from
the Python documentation:

PYTHONPATH

  [...]

  The default search path is installation dependent, but generally
  begins with prefix/lib/pythonversion (see PYTHONHOME above). It is
  always appended to PYTHONPATH.

--

For reference, the errors were typically on the following form:

Traceback (most recent call last):
  File "/usr/lib/command-not-found", line 23, in <module>
    import gettext
  File "/cm/shared/ex3-modules/apps/python/3.7.4/lib/python3.7/gettext.py", line 49, in <module>
    import locale
  File "/cm/shared/ex3-modules/apps/python/3.7.4/lib/python3.7/locale.py", line 16, in <module>
    import re
  File "/cm/shared/ex3-modules/apps/python/3.7.4/lib/python3.7/re.py", line 123, in <module>
    import sre_compile
  File "/cm/shared/ex3-modules/apps/python/3.7.4/lib/python3.7/sre_compile.py", line 17, in <module>
    assert _sre.MAGIC == MAGIC, "SRE module mismatch"
AssertionError: SRE module mismatch

Fix python